services:
  - type: web
    name: climate-api-backend
    env: python
    region: oregon  # Or use "singapore", "frankfurt", etc.
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: WEATHER_API_KEY
        value: YOUR_OPENWEATHERMAP_API_KEY
      - key: OPENROUTER_API_KEY
        value: YOUR_OPENROUTER_API_KEY
      - key: OPENROUTER_BOT_KEY
        value: YOUR_OPENROUTER_BOT_KEY
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
    rootDir: backend
